version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - ./media2:/media2:ro
    restart: "unless-stopped"
    environment:
      - JELLYFIN_PublishedServerUrl=http://${HOST_IP}
    extra_hosts:
      - "host.docker.internal:host-gateway"
